import type { Insight } from '@/lib/types'

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 1) return 'just now'
  if (mins < 60) return `${mins} minute${mins === 1 ? '' : 's'} ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs} hour${hrs === 1 ? '' : 's'} ago`
  const days = Math.floor(hrs / 24)
  return `${days} day${days === 1 ? '' : 's'} ago`
}

function totalTokens(insight: Insight): number {
  return (insight.input_tokens ?? 0) + (insight.output_tokens ?? 0)
}

interface Props {
  insight: Insight | null
}

export default function InsightCard({ insight }: Props) {
  if (!insight) {
    return (
      <div className="bg-white border border-gray-200 rounded-2xl p-8 mb-6">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-3">
          Latest Insight
        </h2>
        <p className="text-gray-400 italic text-sm">
          No insight yet. Click &ldquo;Run scan&rdquo; below to generate one.
        </p>
      </div>
    )
  }

  const cost = insight.cost_usd != null ? `$${Number(insight.cost_usd).toFixed(4)}` : ''

  return (
    <div className="bg-white border border-blue-100 rounded-2xl p-8 mb-6 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wide">
          Latest Insight
        </h2>
        <span
          className="text-xs text-gray-400"
          title={new Date(insight.generated_at).toLocaleString()}
        >
          {relativeTime(insight.generated_at)}
        </span>
      </div>
      <p className="text-gray-800 leading-relaxed whitespace-pre-line text-sm">
        {insight.summary_text}
      </p>
      <p className="mt-4 text-xs text-gray-400">
        Generated by {insight.model}
        {cost ? ` · ${cost}` : ''}
        {` · ${totalTokens(insight).toLocaleString()} tokens`}
      </p>
    </div>
  )
}
